// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CertificationController from "./certification_controller"
application.register("certification", CertificationController)

import CommentController from "./comment_controller"
application.register("comment", CommentController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ImagesController from "./images_controller"
application.register("images", ImagesController)

import ManagementController from "./management_controller"
application.register("management", ManagementController)

import MypageController from "./mypage_controller"
application.register("mypage", MypageController)

import PlaceController from "./place_controller"
application.register("place", PlaceController)

import PostController from "./post_controller"
application.register("post", PostController)

import SelectmenuController from "./selectmenu_controller"
application.register("selectmenu", SelectmenuController)

import TagController from "./tag_controller"
application.register("tag", TagController)

import UserController from "./user_controller"
application.register("user", UserController)
